version: '3.8'

services:
  cargo:
    build: ./app
    command: bash -c 'while !</dev/tcp/cargo-db/5432; do sleep 1; done; python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    depends_on:
      - cargo-db

  cargo-db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cargo_dev

  redis:
    image: redis:alpine
  celery:
    build: ./app
    command: celery -A drf_project worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./app/.env
    depends_on:
      - redis
  celery-beat:
    build: ./app
    command: celery -A drf_project beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./app/.env
    depends_on:
      - redis

volumes:
  postgres_data:
